# This task remove configuration from previous installation

#remove files that kubeadm create
- name: Remove files from previous installation
  ansible.builtin.file:
    path: "{{item}}"
    state: absent
  with_items:
  - /etc/kubernetes/manifests/kube-apiserver.yaml
  - /etc/kubernetes/manifests/kube-controller-manager.yaml
  - /etc/kubernetes/manifests/kube-scheduler.yaml
  - /etc/kubernetes/manifests/etcd.yaml
  - /var/lib/etcd

#stop kubelet service
- name: Stop kubelet
  ansible.builtin.systemd:
    state: stoped
    name: docker
